In [1]:
#Comparison Operators as ufuncs

In [3]:
import numpy as np

In [4]:
x=np.array([1,2,3,4,5,6])

In [5]:
x<3

array([ True,  True, False, False, False, False])

In [6]:
x>4

array([False, False, False, False,  True,  True])

In [7]:
x>=4

array([False, False, False,  True,  True,  True])

In [8]:
x<=2

array([ True,  True, False, False, False, False])

In [10]:
x!=4

array([ True,  True,  True, False,  True,  True])

In [11]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False, False])

In [12]:
x**2

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [13]:
2**x

array([ 2,  4,  8, 16, 32, 64], dtype=int32)

In [14]:
2*x

array([ 2,  4,  6,  8, 10, 12])

In [15]:
#two dimension example

In [16]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [17]:
np.less(x,6)

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [18]:
rng

In [20]:
#working with arrays
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [21]:
#counting entries
# how many values less than 6?
np.count_nonzero(x < 6)

8

In [23]:
np.sum(x<6)

8

In [24]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [25]:
# how many values less than 6 in each column?
np.sum(x < 6, axis=0)

array([2, 2, 2, 2])

In [2]:
import numpy as np

In [3]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [4]:
# are there any values greater than 8?
np.any(x > 8)

True

In [5]:
#are all values less than 8
np.all(x < 8)

False

In [6]:
# are there any values less than zero?
np.any(x < 0)

False

In [7]:
# are there any values less than zero?
np.any(x < 0)

False

In [10]:
# are all values equal to 6?
np.all(x == 6)

False

In [11]:
# are all values equal to 6?
np.all(x != 6)

False

In [12]:
# are all values equal to 15?
np.all(x != 15)

True

In [15]:
#are all values in each row less than 8?
np.all(x < 8, axis=1)

array([ True, False,  True])

In [16]:
#are any values in each column less than 8?
np.any(x < 8, axis=0)

array([ True,  True,  True,  True])

In [17]:
#Boolean operators

In [19]:
#boolen masking

In [20]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [21]:
x< 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [22]:
x[x<5]

array([0, 3, 3, 3, 2, 4])

In [23]:
# construct a mask of all rainy days
rainy = (inches > 0)
# construct a mask of all summer days (June 21st is the 172nd day)
summer = (np.arange(365) - 172 < 90) & (np.arange(365) - 172 > 0)
print("Median precip on rainy days in 2014 (inches): ",
np.median(inches[rainy]))
print("Median precip on summer days in 2014 (inches): ",
np.median(inches[summer]))
print("Maximum precip on summer days in 2014 (inches): ",
np.max(inches[summer]))
print("Median precip on non-summer rainy days (inches):",
np.median(inches[rainy & ~summer]))

NameError: name 'inches' is not defined

In [24]:
bool(42), bool(0)

(True, False)

In [26]:
bool(42 and 0)

False

In [27]:
bool(42 or 0)

True

In [28]:
bool(42 & 0)

False

In [29]:
bool(45 | 0)

True

In [30]:
bin(42)

'0b101010'

In [31]:
bin(59)

'0b111011'

In [32]:
bin(42 | 59)

'0b111011'

In [33]:
bin(42 & 59)

'0b101010'

In [34]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

array([ True,  True,  True, False,  True,  True])

In [35]:
A & B

array([ True, False,  True, False,  True, False])

In [36]:
A or B

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [37]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [38]:
(x > 4) and (x < 8)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()