In [34]:
import pandas as pd
pd.__version__

'0.23.4'

In [10]:
data = pd.Series([0.25, 0.5, 0.75, 1])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [14]:
#similar to a numpy array
data.values
#to get info about the index
data.index
#data can be accessed via yhhe familiar python square bracket notation
data[0]
data[]


0.25

In [16]:
#Series as generalized NumPy array
#string as index
data2 =  pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
data2
data2['a']

0.25

In [24]:
#Series as specialized dictionary
population_dict = {'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}
population = pd.Series(population_dict)
population
#supports operations such as slicing
population['California':'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

In [25]:
#data can be scalar
pd.Series(5, index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [28]:
####Data frame
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
 'Florida': 170312, 'Illinois': 149995}
area_dict
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [32]:
states = pd.DataFrame({'population': population,
 'area': area})
states.index
states.columns

Index(['population', 'area'], dtype='object')

In [38]:
#constaructing a dataframe
# 1) from a singel series
pd.DataFrame(population, columns=['population'])
# 2) from a list of dicts
data = [{'a':i, 'b':2* i}
        for i in range(6)]
pd.DataFrame(data)

###if keys in the dictonary are missing Pandas will fill them up with NaN
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])
# 3) from a dictionary of Deries objects


a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [11]:
#Operating on Data in Pandas
import pandas as pd
import numpy as np
rng = np.random.RandomState(0)
ser = pd.Series(rng.randint(0, 10, 4))
print(ser)
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
 columns=['A', 'B', 'C', 'D'])
print(df)
np.exp(ser)
np.sin(df * np.pi/ 4)

0    5
1    0
2    3
3    3
dtype: int32
   A  B  C  D
0  7  9  3  5
1  2  4  7  6
2  8  8  1  6


A             B         C         D
0 -7.071068e-01  7.071068e-01  0.707107 -0.707107
1  1.000000e+00  1.224647e-16 -0.707107 -1.000000
2 -2.449294e-16 -2.449294e-16  0.707107 -1.000000

In [17]:
#index Alignment
#on  two Series or DataFrame objects pandas align indices in the process of performing the operation
area =pd.Series({'Alaska': 1723337, 'Texas': 695662,
 'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127}, name='population')
print(population/ area)
print(area.index | population.index)

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64
Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')


In [23]:
# index alignment in DataFrame
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
 columns=list('AB'))
A
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
 columns=list('BAC'))
print(A, B)
print(A + B)

    A   B
0  10  11
1   4   6    B  A  C
0  4  4  3
1  4  4  8
2  4  3  7
      A     B   C
0  14.0  15.0 NaN
1   8.0  10.0 NaN
2   NaN   NaN NaN


In [28]:
#Operation between DataFrame and series
A = rng.randint(10, size=(3,4))
print(A)
A - A[0]

[[4 6 8 2]
 [3 0 0 6]
 [0 6 3 3]]


array([[ 0,  0,  0,  0],
       [-1, -6, -8,  4],
       [-4,  0, -5,  1]])

In [46]:
#Handling missing data
#to drop null values
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data.dropna()
#to drop null values along a different axis, axis = 1 drops all columns containing null
df.dropna(axis = 'columns')
## how = 'any' drops row andcolumn containing a null value will be dropped
## how = 'all' drops row/ coulumns that are all null values
df.dropna(axis='columns', how='all')

## to specify a thresh parameter  minimum number of non-null values for the row/column to be kept:
df.dropna(axis='rows', thresh=3)

##Filling null values
## sometime you'd rather replace NaN with valid values. It might be a single number like zero pr be 
## some sort of imputation or in terpolation from the food values
print(data.fillna(0))
#We can specify a forward-fill to propagate the previous value forward:
print(data.fillna(method='ffill'))
#we can specify a back-fill to propagate the next values backward:
print(data.fillna(method='bfill'))

# we can also specify an axis along which the fills take place:
df = pd.DataFrame([[1, np.nan, 2],
     [2, 3, 5],
     [np.nan, 4, 6]])
df.fillna(method='ffill', axis=1)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64
a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64
a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64


0    1    2
0  1.0  1.0  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0

In [61]:
#Hierarchical indexing
index = [('California', 2000), ('California', 2010),
        ('New York', 2000), ('New York', 2010),
        ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
                18976457, 19378102,
                20851820, 25145561]
pop = pd.Series(populations, index=index)
print(pop)
index = pd.MultiIndex.from_tuples(index)
print(index)
pop_in = pop.reindex(index)
# to convert a multiplyindexed Series into a conventionally indexed DataFrame:
pop_df = pop_in.unstack()
pop_df.stack()

###multidemension indexing 
df = pd.DataFrame(np.random.rand(4, 2),
 index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
 columns=['data1', 'data2'])
df

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64
MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])


data1     data2
a 1  0.849143  0.205150
  2  0.964481  0.307463
b 1  0.464875  0.011497
  2  0.765967  0.642198

In [62]:
###data aggregation on multi-Indices

NameError: name 'health_data' is not defined

In [65]:
##Combining Datasets Concat and Append
import numpy as np
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c:[str(c) + str(i) for i in ind]
           for c in cols}
    return pd.DataFrame(data, ind)
make_df('ABC', range(3))

# pd.concat(), which has a similar syntax to np.concatenate
# but contains a number of options that we’ll discuss momentarily:
##the append()method
df1, df2
df1.append(df2)

#merge
pd.merge(df1, df2)
#join
df1.join(df2)


NameError: name 'df1' is not defined

In [83]:
###Aggregation and Grouping
#planets Data
import seaborn as sns
planets = sns.load_dataset('planets')
#print(planets)
#get the dim
planets.shape
planets.head()
ser = pd.Series(rng.rand(5))
ser.sum()
ser.mean()
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [89]:
#GroupBy: Split, Apply, Combine
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
     'data': range(6)}, columns=['key', 'data'])
#group by
df.groupby('key').sum()
#aggregate
df.groupby('key').aggregate(['min', np.median, max])
#filtering
df.groupby('key').filter()

TypeError: filter() missing 1 required positional argument: 'func'