In [1]:
#The Basics of NumPy Arrays

In [2]:
import numpy as np

In [3]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [4]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

x1 ndim:  1
x1 shape: (6,)
x1 size:  6


In [6]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


In [7]:
#data typre of array
print("dtype:", x3.dtype)

dtype: int32


In [8]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [10]:
print("itemsize: ",x1.itemsize, "bytes")

itemsize:  4 bytes


In [11]:
print("nbytes: ",x1.nbytes, "bytes")

nbytes:  24 bytes


In [12]:
#Array Indexing: Accessing Single Elements

In [13]:
x1

array([5, 0, 3, 3, 7, 9])

In [14]:
x1[0]

5

In [15]:
x1[2]

3

In [16]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [17]:
x2[2,3]

7

In [18]:
x2[1,2]

8

In [19]:
x2[2,2]

7

In [21]:
#modifying x2 array
x2[0,3]=9
x2

array([[3, 5, 2, 9],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [22]:
x1

array([5, 0, 3, 3, 7, 9])

In [24]:
x1[2]=5
x1

array([5, 0, 5, 3, 7, 9])

In [25]:
#Array Slicing: Accessing Subarrays

In [27]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [30]:
x[5:]# elements after index 5

array([5, 6, 7, 8, 9])

In [31]:
x[::2]  # every other element even numbers

array([0, 2, 4, 6, 8])

In [32]:
x[::3]  # every other element divisible by 3 

array([0, 3, 6, 9])

In [33]:
x[1::2]  # every other element, starting at index 1  [odd numbers]

array([1, 3, 5, 7, 9])

In [35]:
x[::4]  # every other element divisible by 4

array([0, 4, 8])

In [36]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [37]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [40]:
x[:8:-2]  # reversed every other from index 5

array([9])

In [41]:
#Multi-dimensional subarrays

In [42]:
x2

array([[3, 5, 2, 9],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [43]:
x2[:2, :3]  # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [45]:
x2[:3, :1]  # three rows, one column

array([[3],
       [7],
       [1]])

In [46]:
x2[:2, :3]  # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [47]:
x2[:3, ::2]  # all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [48]:
x2[::-1, ::-1] #reversed multidimensional array

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [9, 2, 5, 3]])

In [49]:
print(x2[:, 0])  # first column of x2

[3 7 1]


In [54]:
print(x2[:, 1])  # second column of x2

[5 6 6]


In [52]:
 print(x2[0, :])  # first row of x2

[3 5 2 9]


In [53]:
print(x2[1, :])  # second row of x2


[7 6 8 8]


In [55]:
print(x2[0])  # equivalent to x2[0, :]

[3 5 2 9]


In [56]:
print(x2[2])

[1 6 7 7]


In [57]:
#subarrays as no-copy views

In [58]:
x2

array([[3, 5, 2, 9],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [59]:
print(x2)

[[3 5 2 9]
 [7 6 8 8]
 [1 6 7 7]]


In [60]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [62]:
x2_sub[0,0]=99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [63]:
print(x2)

[[99  5  2  9]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [64]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [66]:
x2_sub_copy[0,0]=49
print(x2_sub_copy)

[[49  5]
 [ 7  6]]


In [67]:
print(x2)

[[99  5  2  9]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [68]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [70]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [71]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [74]:
# column vector via neewaxis
x[: ,np.newaxis]

array([[1],
       [2],
       [3]])

In [75]:
#Array Concatenation and Splitting

In [76]:
#Concatenation of arrays

In [77]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [78]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [79]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [80]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [81]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [82]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [83]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# horizontal stack the arrays
np.hstack([x, grid])

ValueError: all the input arrays must have same number of dimensions

In [84]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [85]:
#Splitting of arrays

In [86]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [87]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [90]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
