# INTRODUCTION TO NUMPY

## Numpy Arrays

### Arrays from Python lists

In [2]:
import numpy as np

# Create an array of integers
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

### NB: Numpy is constrained to contain arrays of same type. If they are not, numpy upcasts them. Use the `dtype` keyword to explicitly typecast the arrays.

In [4]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
## Multidimensional array using a list of lists
np.array([range(i, i + 3) for i in [2, 3, 4]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

### Arrays from Scratch

In [18]:
# A length-10 integer array filled with zeros
np.zeros(10, dtype='int')

# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=np.float)

# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)

np.arange(0, 20, 2)

# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

# Create a 3x3 array of uniformly distributed
# random values between 0 and 1

np.random.random((3,3))

# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

# Create a 3x3 identity matrix
np.eye(3, dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Numpy Array Attributes

In [20]:
# Seed the Random number generator to ensure it produces same set of numbers on each call
np.random.seed(0)

# create 3 arrays, 1-dim, 2-dim and 3-dim of numbers between 1 and 10
array1 = np.random.randint(10, size=6)
array2 = np.random.randint(10, size=(3, 4))
array3 = np.random.randint(10, size=(3, 4, 5))

'''
    The main attributes:
        ndim - Number of dimensuins
        shape - size of each dimension
        size - total size of the array
        dtype - data type of the array
'''

print("Array2 ndim: ", array2.ndim)
print("Array2 shape: ", array2.shape)
print("Array2 size: ", array2.size)
print("Array2 dtype: ", array2.dtype)

Array2 ndim:  2
Array2 shape:  (3, 4)
Array2 size:  12
Array2 dtype:  int32


## Array Indexing - Accessing single array elements

In [24]:
# Access the first element in array 1
print(array1)
first_array1_element = array1[0]
print(first_array1_element)

# Access the first element in second row of array 2
print(array2)
array2_element = array2[0, 0]
print(array2_element)

[5 0 3 3 7 9]
5
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
