# Testing of Miscellaneous code

In [7]:
# Numpy version
import numpy as np
np.__version__

# numpy namespace and docs
np.random.randint?

## Python arrays

In [3]:
import array

# create a list of 10 items
my_list = list(range(10))

# Create an array
# The 'i' is a type code indicating all the contents are integers
my_array = array.array('i', my_list)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
print(np.random.randint(10, size=(3, 4, 5)))
x1 = np.random.randint(10, size=6)
x1

[[[1 1 4 1 2]
  [9 2 1 6 0]
  [5 6 9 9 2]
  [7 4 4 0 5]]

 [[3 1 0 6 3]
  [5 3 5 6 5]
  [8 9 5 4 1]
  [6 6 2 7 9]]

 [[2 8 0 1 8]
  [1 5 9 1 7]
  [5 9 6 7 5]
  [6 3 9 3 0]]]


array([0, 6, 7, 6, 8, 1])