In [1]:
#python lists
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
#list of intergers
type(L[0])

int

In [3]:
#list of strings
L2 = [str(c)for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
type (L2[0])

str

In [5]:
#Heterogeneous lists
L3 = [True, "2", 3.0,4]
[type(item)for item in L3]

[bool, str, float, int]

In [6]:
import array
L = list(range(10))
A = array.array('l',L)
A

array('l', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np

In [8]:
#integer arrray:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [9]:
#numpy arrays should all be the same type
np.array ([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
#explicitly set data type using: dtype
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [11]:
#nested lists result in multidimensional arrays
np.array([range(i, i+3)for i in[2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [12]:
#Creating arrays from scratch
#Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
#create a 3*5 floating point array filles with 1s
np.ones((3*5),dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
#create a 3*5 array filled with 3.14
np.full((3*5),3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14,
       3.14, 3.14, 3.14, 3.14])

In [15]:
#create an array filled with a linear sequence
#staring at 0, ending at 20, stepping by 2
#(this is similiar tobuilt-in range()function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
#create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
#create a 3*3 arrayof uniformly distributed
#random values between 0 and 1
np.random.random((3,3))

array([[0.16027575, 0.10535419, 0.41468123],
       [0.84953584, 0.49931432, 0.10433389],
       [0.85732935, 0.0608156 , 0.23724246]])

In [18]:
#create an array of normally distributed random values
#with a mean of 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 1.52741179, -1.62672963, -1.00973005],
       [-0.38937277,  0.17090314, -1.02050763],
       [-1.20426936, -0.9452142 ,  0.43182025]])

In [19]:
#create a 3*3 array of random integers in the interval [0,10]
np.random.randint(0,10,(3*3))

array([3, 5, 3, 6, 1, 2, 0, 7, 6])

In [20]:
#create a 3*3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
#create an uninitilized array of three integers
#the values will be whatever happens to already exist at that
#momory location
np.empty(3)

array([1., 1., 1.])