In [1]:
import numpy as np
import pandas as pd
# use Pandas to extract rainfall inches as a NumPy array
rainfall = pd.read_csv('data/Seattle2014.csv')['PRCP'].values
inches = rainfall / 254  
# 1/10mm -> inches
inches.shape

FileNotFoundError: File b'data/Seattle2014.csv' does not exist

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set()  # set plot styles

In [ ]:
plt.hist(inches, 40)

In [5]:
#Comparison arrays
x = np.array([1,2,3,4,5])

In [6]:
x<3 #greater than

array([ True,  True, False, False, False])

In [7]:
x > 3 #less than

array([False, False, False,  True,  True])

In [8]:
x <= 3 #less than or equal to

array([ True,  True,  True, False, False])

In [9]:
x >= 3 #greater than or equal to

array([False, False,  True,  True,  True])

In [10]:
x !=3 #not equal to

array([ True,  True, False,  True,  True])

In [11]:
x==3 #equal to

array([False, False,  True, False, False])

In [12]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [13]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [14]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [15]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [16]:
#counting entries
# how many values less than 6?
np.count_nonzero(x < 6)

8

In [17]:
np.sum(x < 6)

8

In [18]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [19]:
# are there any values greater than 8?
np.any(x > 8)

True

In [20]:
# are there any values less than zero?
np.any(x < 0)

False

In [21]:
# are all values less than 10?
np.all(x < 10)

True

In [22]:
# are all values equal to 6?
np.all(x == 6)


False

In [23]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)

array([ True, False,  True])

In [24]:
np.sum((inches > 0.5) & (inches < 1))

NameError: name 'inches' is not defined

In [25]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [26]:
x<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [27]:
#Masking booleans
x[x < 5]

array([0, 3, 3, 3, 2, 4])

In [28]:
bool(42), bool(0)

(True, False)

In [29]:
bool(42 and 0)


False

In [30]:
bool(42 or 0)

True

In [31]:
bin(42)


'0b101010'

In [32]:
bin(59)

'0b111011'

In [33]:
bin(42 & 59)

'0b101010'

In [34]:
bin(42 | 59)

'0b111011'

In [35]:
 A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B


array([ True,  True,  True, False,  True,  True])

In [36]:
A or B


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [37]:
x = np.arange(10)
(x > 4) & (x < 8

SyntaxError: unexpected EOF while parsing (<ipython-input-37-193fb5f013b1>, line 2)

In [38]:
(x > 4) and (x < 8)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()