In [1]:
import numpy as np

In [2]:
#summing values in an array
#python
L = np.random.random(100)
sum(L)

47.568622834400905

In [3]:
#summing values in an array
#Ipython
np.sum(L)

47.568622834400905

In [4]:
#Numpy code is computed more quickly because itexecutes the operation in a compiled code
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)


208 ms ± 92.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.25 ms ± 356 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
#minimium and maximum
#PYTHON
min(big_array),max(big_array)

(1.7368073355061853e-06, 0.9999989951135306)

In [6]:
#minimium and maximum
#IPYTHON
np.min(big_array),np.max(big_array)

(1.7368073355061853e-06, 0.9999989951135306)

In [7]:
%timeit min(big_array)
%timeit np.min(big_array)

140 ms ± 14.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
766 µs ± 25.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
print(big_array.min(), big_array.max(), big_array.sum())

1.7368073355061853e-06 0.9999989951135306 500143.30763825466


In [9]:
#multidimensional arrays
M = np.random.random((3, 4))
print(M)

[[0.74243975 0.54788214 0.98648319 0.79746282]
 [0.44228935 0.31499601 0.08265588 0.36535975]
 [0.19644784 0.45305076 0.46681997 0.35137684]]


In [10]:
M.sum()

5.747264314006822

In [11]:
#Aggregation functions take an additional argument specifying the axis along which the aggregate is computed
M.min(axis = 0)

array([0.19644784, 0.31499601, 0.08265588, 0.35137684])

In [12]:
#The axis keyword specifiestthe dimension of the array that will be collapsed
M.max(axis = 1)

array([0.98648319, 0.44228935, 0.46681997])

In [13]:
#example: what is the average height of US presidents?
!head - 4data/president_height.csv
order,name,height(cm) 
1,George Washington,189
2,John Adams,170 
3,Thomas Jefferson,189

SyntaxError: invalid syntax (<ipython-input-13-35ae1bc4058f>, line 4)