In [1]:
import numpy as np
np.random.seed(0)
#seed for reproductivity

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2=np.random.randint(10, size=(3,4))#two dimensional array
x3=np.random.randint(10, size=(3,4,5))#three-dimensional array

In [2]:
print("x3 ndim:", x3.ndim)
print("x3 size:", x3.size)
print("x3 shape:", x3.shape)

x3 ndim: 3
x3 size: 60
x3 shape: (3, 4, 5)


In [3]:
print("dtype:", x3.dtype)

dtype: int32


In [4]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [5]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x1[0]

5

In [7]:
x1[5]

9

In [8]:
#To index from the end of the array, you can use negative indices:
x1[-1]

9

In [9]:
x1[-2]

7

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
#In a multidimensional array, you access items using a comma-separated tuple of indices:
x2[0,0]

3

In [12]:
x2[2,0]

1

In [13]:
x2[2,-1]

7

In [14]:
#You can also modify values using any of the above index notation:
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [15]:
# NumPy arrays have a fixed type.
#this will be truncated
x1[0]= 3.5423
x1

array([3, 0, 3, 3, 7, 9])

In [16]:
#One-dimensional subarrays
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#first five elements
x[:5]

array([0, 1, 2, 3, 4])

In [18]:
#elements after index 5
x[5:]

array([5, 6, 7, 8, 9])

In [19]:
#middle subarray
x[4:7]

array([4, 5, 6])

In [20]:
#every other element
x[::2]

array([0, 2, 4, 6, 8])

In [21]:
#every other element starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

In [22]:
#all elements reversed
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
#reversed every other element from index 5
x[5::-2]

array([5, 3, 1])

In [24]:
#Multidimensional Sub Arrays
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [25]:
#Two rows, three columns
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [26]:
#all rows, every other column
x2[:3,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [27]:
#reversed subarrays
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [28]:
#accessing arrays and columns
#first column of x2
#combining indexing and slicing
print(x2[:,0])

[12  7  1]


In [29]:
#first row of x2
print(x2[0,:])

[12  5  2  4]


In [30]:
#equivalent tox2[0, :]
#In the case of row access, the empty slice can be omitted for a more compact syntax:
print(x2[0])

[12  5  2  4]


In [31]:
#Subarrays as no-copy views
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [32]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [33]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [34]:
 print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [35]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [36]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [37]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [38]:
#if you want to put the numbers 1 through 9 in a 3×3 grid
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
x = np.array([1,2,3])

#row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [44]:
#row vector in new axis
x[np.newaxis, :]

array([[1, 2, 3]])

In [45]:
#column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [46]:
#colum vector via new axis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [48]:
#Concatenation of arrays
x = np.array([1, 2, 3])
 y = np.array([3, 2, 1])
 np.concatenate([x, y])


array([1, 2, 3, 3, 2, 1])

In [49]:
#joining more than two arrays
z = [99, 99, 99]
print(np.concatenate([x, y, z]))


[ 1  2  3  3  2  1 99 99 99]


In [50]:
#two-dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])


In [52]:
 # concatenate along the first axis
 np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [54]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
        # vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [58]:
 # horizontally stack the arrays
y = np.array([[99],
             [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [59]:
#Splitting of arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [60]:
grid = np.arange(16).reshape((4, 4))
grid


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)
