In [1]:
import numpy
numpy.__version__

'1.16.2'

In [2]:
import numpy as np

In [3]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(l[0])

int

In [6]:
l2 = [str(c)for c in l]
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(l2[2])

str

In [9]:
l3 = [True, '2', 3.0, 4]
[type(item)for item in l3]

[bool, str, float, int]

In [10]:
import array
l = list(range(10))
a = array.array('i', l)
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#integer array
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [12]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [13]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [14]:
#nested lists result in multidimensional arrays
np.array([range(i, i+3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [15]:
#create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
#creating a 3*5 floating-point array filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#create a 3*5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [18]:
#create an array filled with linear sequence
#starting at 0, ending at 20, stepping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
#create an array of five values evenly spaced btwn 0 & 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
#create a 3*3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])